Array Class Reference
Dynamic integer array class with bounds checking and I/O operators Array class: like an int array (retains all functionality) but also includes additional features: -- allows input and output of the whole array -- allows for comparison of 2 arrays, element by element -- allows for assignment of 2 arrays -- size is part of the class (so no longer needs to be passed) -- includes range checking, program terminates for out-of-bound subscripts.
#include <array.h>
Public Member Functions
Array (int arraySize=10)
Default constructor for Array class.
Array (const Array &init)
Copy constructor for Array class.
~Array ()
Destructor for Array class.
int getSize () const
Get the size of the array.
const Array & operator= (const Array &right)
Assignment operator for Array class.
bool operator== (const Array &right) const
Equality comparison operator.
bool operator!= (const Array &right) const
Inequality comparison operator.
int & operator[] (int subscript)
Subscript operator for array access.
Static Public Member Functions
static int getArrayCount ()
Get the number of Array objects instantiated.
Private Attributes
int * ptr
pointer to first element of array
int size
size of the array
Static Private Attributes
static int arrayCount = 0
Friends
istream & operator>> (istream &input, Array &a)
Overloaded input operator for class Array.
ostream & operator<< (ostream &output, const Array &a)
Overloaded output operator for class Array.
Detailed Description
Dynamic integer array class with bounds checking and I/O operators Array class: like an int array (retains all functionality) but also includes additional features: -- allows input and output of the whole array -- allows for comparison of 2 arrays, element by element -- allows for assignment of 2 arrays -- size is part of the class (so no longer needs to be passed) -- includes range checking, program terminates for out-of-bound subscripts.
Driver program for the Array class This program tests the functionality of the Array class including:
Dynamic integer array class with bounds checking and I/O operators.
Assumptions: -- size defaults to a fixed size of 10 if size is not specified -- array elements are initialized to zero -- user must enter valid integers when using >> -- in <<, integers are displayed 10 per line
Array class: like an int array (retains all functionality) but also includes additional features: -- allows input and output of the whole array -- allows for comparison of 2 arrays, element by element -- allows for assignment of 2 arrays -- size is part of the class (so no longer needs to be passed) -- includes range checking, program terminates for out-of-bound subscripts
Implementation and assumptions: -- size defaults to a fixed size of 10 if size is not specified -- array elements are initialized to zero -- user must enter valid integers when using >> -- in <<, integers are displayed 10 per line
Construction and destruction
Input and output operators
Comparison operators (== and !=)
Assignment operator
Subscript operator with bounds checking
Static member function for counting instances
Note
Ensure to provide valid integer input when prompted
Test
Test Comprehensive test of Array class features
Definition at line 32 of file array.h.
Constructor & Destructor Documentation
Array() [1/2]
Array::Array (int arraySize = 10)
Default constructor for Array class.
Default constructor.
Parameters
in arraySize Initial size of the array (defaults to 10)
Precondition
None
Postcondition
ptr points to array of size arraySize, all elements zero, arrayCount is incremented
Returns
Newly constructed Array object
Note
Negative input values result in the default size of 10
Test
Test Test with positive, negative, and zero sizes
Parameters
in arraySize Initial size of the array
Precondition
None
Postcondition
ptr points to an array of size arraySize and all elements of the array have been initialized to zero. arrayCount is incremented. Negative input values result in the default size of 10
Returns
Newly constructed Array object
Note
Uses assert to ensure memory allocation succeeds
Definition at line 44 of file array.cpp.
{
    ++arrayCount;
    size = (arraySize > 0 ? arraySize : 10);
    ptr = new int[size];
    assert(ptr != NULL);
    for (int i = 0; i < size; i++)
        ptr[i] = 0;
}
References arrayCount, ptr, and size.
Referenced by Array(), operator!=(), operator<<, operator=(), operator==(), and operator>>.
Array() [2/2]
Array::Array (const Array & init)
Copy constructor for Array class.
Copy constructor.
Parameters
in init Array to copy from
Precondition
init.ptr points to an array of size at least init.size
Postcondition
init is copied into *this, arrayCount is incremented
Returns
Newly constructed Array object as a copy of init
Note
Creates deep copy of the array
Test
Test Test copying arrays of various sizes
Parameters
in init Array to copy from
Precondition
init.ptr points to an array of size at least init.size
Postcondition
init is copied into *this, arrayCount is incremented
Returns
Newly constructed Array object as a copy of init
Note
Creates deep copy of the array
Definition at line 65 of file array.cpp.
{
    ++arrayCount;
    size = init.size;
    ptr = new int[size];
    assert(ptr != NULL);
    for (int i = 0; i < size; i++)
        ptr[i] = init.ptr[i];
}
References Array(), arrayCount, ptr, and size.
~Array()
Array::~Array ()
Destructor for Array class.
Destructor.
Precondition
ptr points to memory on the heap
Postcondition
Array for ptr is deallocated, arrayCount is decremented
Returns
None
Note
Automatically called when Array object goes out of scope
Precondition
ptr points to memory on the heap
Postcondition
Array for ptr is deallocated, arrayCount is decremented
Returns
None
Note
Automatically called when object goes out of scope
Definition at line 84 of file array.cpp.
{
    --arrayCount;
    delete[] ptr;
}
References arrayCount, and ptr.
Member Function Documentation
getArrayCount()
int Array::getArrayCount () [static]
Get the number of Array objects instantiated.
Precondition
None
Postcondition
Returns the number of arrays
Returns
Count of Array objects currently instantiated
Note
Static member function
Test
Test Verify count increases with construction and decreases with destruction
Precondition
None
Postcondition
Returns the number of arrays
Returns
Number of Array objects currently instantiated
Note
Static member function
Definition at line 187 of file array.cpp.
{ return arrayCount; }
References arrayCount.
Referenced by main().
getSize()
int Array::getSize () const
Get the size of the array.
Precondition
None
Postcondition
Returns the size of the array
Returns
Current size of the array
Test
Test Verify size matches what was specified during construction
Precondition
None
Postcondition
Returns the size of the array
Returns
Size of the array
Definition at line 97 of file array.cpp.
{ return size; }
References size.
Referenced by main().
operator!=()
bool Array::operator!= (const Array & right) const
Inequality comparison operator.
Inequality operator.
Parameters
in right Array to compare with
Precondition
ptr and right.ptr point to arrays with size at least size and right.size, respectively
Postcondition
false is returned if the arrays have the same size and elements, true otherwise
Returns
true if arrays are not equal, false otherwise
Test
Test Test with equal and unequal arrays
Remarks
Uses operator== for implementation
Parameters
in right Array to compare with
Precondition
ptr and right.ptr point to arrays with size at least size and right.size, respectively
Postcondition
false is returned if the arrays have the same size and elements true is return otherwise
Returns
true if arrays are not equal, false otherwise
Remarks
Uses operator== for implementation
Definition at line 158 of file array.cpp.
{
    return !(*this == right);
}
References Array().
operator=()
const Array & Array::operator= (const Array & right)
Assignment operator for Array class.
Assignment operator.
Parameters
in right Array to assign from
Precondition
right.ptr points to an array of size at least right.size
Postcondition
*this is assigned the same array as right
Returns
Reference to the assigned array
Note
Self-assignment is checked and handled properly
Test
Test Test assignment between arrays of different sizes
Parameters
in right Array to assign from
Precondition
right.ptr points to an array of size at least right.size
Postcondition
*this is assigned the same array as right
Returns
Reference to *this
Note
Handles self-assignment and creates deep copy
Definition at line 109 of file array.cpp.
{
    if (&right != this)
    {
        delete[] ptr;
        size = right.size;
        ptr = new int[size];
        assert(ptr != NULL);
        for (int i = 0; i < size; i++)
            ptr[i] = right.ptr[i];
    }
    return *this;
}
References Array(), ptr, and size.
operator==()
bool Array::operator== (const Array & right) const
Equality comparison operator.
Equality operator.
Parameters
in right Array to compare with
Precondition
ptr and right.ptr point to arrays with size at least size and right.size, respectively
Postcondition
true is returned if the arrays have the same size and elements, false otherwise
Returns
true if arrays are equal, false otherwise
Test
Test Test with equal and unequal arrays
Parameters
in right Array to compare with
Precondition
ptr and right.ptr point to arrays with size at least size and right.size, respectively
Postcondition
true is returned if the arrays have the same size and elements false is return otherwise
Returns
true if arrays are equal, false otherwise
Test
Test Test with arrays of different sizes and contents
Definition at line 136 of file array.cpp.
{
    if (size != right.size)
        return false;
    for (int i = 0; i < size; i++)
        if (ptr[i] != right.ptr[i])
            return false;
    return true;
}
References Array(), ptr, and size.
operator[]()
int & Array::operator[] (int subscript)
Subscript operator for array access.
Subscript operator.
Parameters
in subscript Index to access
Precondition
0 <= subscript < size
Postcondition
Returns the array value at position "subscript"
Returns
Reference to array element at given index
Note
Terminates program if subscript is out of range
Test
Test Test valid and invalid indices
Parameters
in subscript Index to access
Precondition
0 <= subscript < size
Postcondition
Returns the array value at position "subscript"
Returns
Reference to array element at given index
Note
Terminates program if subscript out of range
Definition at line 173 of file array.cpp.
{
    assert(0 <= subscript && subscript < size);
    return ptr[subscript];
}
References ptr, and size.
Friends And Related Symbol Documentation
operator<<
ostream & operator<< (ostream & output, const Array & a) [friend]
Overloaded output operator for class Array.
Parameters
in,out output Output stream
in a Array to output
Returns
Reference to the output stream
Precondition
a.ptr must point to an array with size at least a.size
Postcondition
The first a.size elements of a.ptr are sent to output stream
Note
Outputs 10 integers per line with trailing newline
Test
Test Test output formatting with various array sizes
Parameters
in,out output Output stream
in a Array to output
Precondition
a.ptr must point to an array with size at least a.size
Postcondition
The first a.size elements of a.ptr are sent to the output istream 10 per line with a trailing endl
Returns
Reference to the output stream
Note
Outputs 10 integers per line
Definition at line 220 of file array.cpp.
{
    int i;
    for (i = 0; i < a.size; i++)
    {
        output << a.ptr[i] << ' ';
        if ((i + 1) % 10 == 0)
            output << endl;
    }
    if (i % 10 != 0)
        output << endl;
    return output;
}
References Array(), ptr, and size.
operator>>
istream & operator>> (istream & input, Array & a) [friend]
Overloaded input operator for class Array.
Parameters
in,out input Input stream
in,out a Array to read into
Returns
Reference to the input stream
Precondition
a.ptr must point to an array with size at least a.size
Postcondition
The first a.size elements of a.ptr are filled with integers
Note
Reads exactly a.size integers from the stream
Test
Test Test with valid integer input
Parameters
in,out input Input stream
in,out a Array to read into
Precondition
a.ptr must point to an array with size at least a.size
Postcondition
The first a.size elements of a.ptr are filled with integers read from the input istream
Returns
Reference to the input stream
Note
Reads exactly a.size integers from the stream
Definition at line 201 of file array.cpp.
{
    for (int i = 0; i < a.size; i++)
        input >> a.ptr[i];
    return input;
}
References Array(), ptr, and size.
Member Data Documentation
arrayCount
int Array::arrayCount = 0 [static], [private]
of Arrays instantiated (static counter)
Definition at line 162 of file array.h.
Referenced by Array(), Array(), getArrayCount(), and ~Array().
ptr
int* Array::ptr [private]
pointer to first element of array
Definition at line 160 of file array.h.
Referenced by Array(), Array(), operator<<, operator=(), operator==(), operator>>, operator[](), and ~Array().
size
int Array::size [private]
size of the array
Definition at line 161 of file array.h.
Referenced by Array(), Array(), getSize(), operator<<, operator=(), operator==(), operator>>, and operator[]().
The documentation for this class was generated from the following files:
array.h
array.cpp